### ISSUE TITLE
Bump version that only supports Julia v0.4

### ISSUE THREAD

**Issue by milktrader** [JuliaIO/IniFile.jl#15]
This to remove some of the deprecation warnings between Julia 0.3 and 0.4. The latest commit appears to be compatible without warnings.

**Comment by hustf** [comment]
I don't think it should be necessary to remove 0.3 support for this package, because the current issues can be fixed if more people pick up a shovel. 

@milktrader, the latest commit is merged into master, so all one need to do to get a compatible version is

    Pkg.checkout("IniFile")

(getting commits that aren't merged is much harder to do, ref. your Winston comment)

However, that does not get rid of the irritating messages when using 0.4.0 or greater, for example:

    WARNING: Method definition remotecall_fetch(Function, Main.Base.LocalProcess, An
    y...) in module Compat at C:\Users\Fro\.julia\v0.4\Compat\src\Compat.jl:697 over
    written in module Compat at C:\Users\Fro\.julia\v0.4\Compat\src\Compat.jl:697

If these messages appeared once, and then never more, this would be an acceptable price to pay for keeping e.g. Winston alive on Julia 0.3.12. They don't reappear after restarting Julia.

Unfortunately, they reappear after every workspace(), which I for one do all the time. workspace() works as a heavier reset than restarting Julia in this case. I suspect 'Using Base' on line 3 is the reason. 

Tagging ("bumping") wouldn't hurt anyone I believe, but some further improvement could be made to master at this point. Perhaps _VERSION >= v"0.4" && __precompile__()  as a first line? 

But all you have to do to get rid of most of this visual clutter, personally, is editing the text files in Pkg.dir() / package name. Just remove every 'Using Compat' and '@Compat'. Compat just provides forward compatibility for Julia 0.3 in this case.

**Comment by milktrader** [comment]
Yeah I just did a `git pull` to get the latest. This issue addresses tagging a new minor version that supports 0.4 as the floor, for example 0.3.0. This would get rid of Compat and would still leave room to update the versions (0.2.4 up to 0.2.x) that support Julia 0.3. This strategy does require any improvements to the 0.2.x series to come off a new branch just before the master goes to 0.3.0, so not sure this is worth the effort here, just a suggestion.

**Comment by catawbasam** [comment]
Catch 22?
```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating JuliaParser...
INFO: Updating IniFile...
INFO: Computing changes...
ERROR: URLParse can't be installed because it has no versions that support 0.4.1 of julia. You may need to upd
ate METADATA by running `Pkg.update()`
 in error at error.jl:22
```

```
julia> Pkg.checkout("IniFile")
INFO: Checking out IniFile master...
INFO: Pulling IniFile latest master...
ERROR: URLParse can't be installed because it has no versions that support 0.4.1 of julia. You may need to upd
ate METADATA by running `Pkg.update()`
 in error at error.jl:22
```



```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.1 (2015-11-08 10:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32
```

**Comment by catawbasam** [comment]
Purging my package directory and re-installing everything seems to have resolved the issue.

**Comment by hustf** [comment]
Tag a new version please?
https://github.com/timholy/ImageView.jl/pull/91

**Comment by kmsquire** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/4360

**Comment by tkelman** [comment]
Sorry misunderstood. Guess this particular issue is about an 0.4-only version? I don't see that as valuable unless you really feel the need to implement new features that only work on 0.4.

**Comment by quinnj** [comment]
IniFile.jl now has a lower bound of julia 0.6
