### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by bluesmoon** [JuliaIO/IniFile.jl#17]
Is there any documentation for this module? How does one figure out how to use it?

**Comment by hustf** [comment]
Hello, bluesmoon. Good question. I believe this package is now used directly by Winston and Winston only. That is a plotting package which used to be fronted in julialang.org and in books, and since it is an old package it is used by some cool and interesting packages like Openstreetmap and Weave.

I suggest you have a look at that package for how to use it, and possibly on your windows hard disk for how other people use .ini files.

**Comment by bluesmoon** [comment]
I'm familiar with ini files.  What I'm asking for is a published list of methods in this module and how to use them.  I ended up reading the `runtests.jl` file and got some hints from there.

**Comment by tknopp** [comment]
unfortunately this package does not have docs.

**Comment by quinnj** [comment]
added in 4777243
